version: "3.7"

services:
  keycloak:
    image: keycloak/keycloak:26.0.2
    command:
    - start-dev
    - --spi-email-sender-provider=sendgrid-email-sender-provider
    - --spi-email-template-provider=sendgrid-email-template-provider
    - --spi-email-template-sendgrid-email-template-provider-template-smtp-test=d-188
    - --spi-email-template-sendgrid-email-template-provider-template-password-reset=d-188
    environment:
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./target/sendgrid-provider-jar-with-dependencies.jar:/opt/keycloak/providers/sendgrid-provider-jar-with-dependencies.jar
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
